name: .NET Deploy To Render

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest


    env: 
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Validate Render deploy hook environment variable
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "ERROR: RENDER_DEPLOY_HOOK is not set."
            exit 1
          else
            echo "Render deploy hook detected (hidden)."
          fi

      - name: Trigger Render deploy hook
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
